I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/credits.rpy", line 4, in script
    with Pause(45)
IOError: Couldn't find file 'credits3.webm'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/credits.rpy", line 4, in script
    with Pause(45)
  File "E:\github_ics3u\renpy-6.99.13-sdk\renpy\ast.py", line 1289, in execute
    renpy.exports.with_statement(trans, paired)
  File "E:\github_ics3u\renpy-6.99.13-sdk\renpy\exports.py", line 1406, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "E:\github_ics3u\renpy-6.99.13-sdk\renpy\display\core.py", line 2123, in do_with
    clear=clear)
  File "E:\github_ics3u\renpy-6.99.13-sdk\renpy\display\core.py", line 2553, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "E:\github_ics3u\renpy-6.99.13-sdk\renpy\display\core.py", line 3104, in interact_core
    renpy.audio.audio.periodic()
  File "E:\github_ics3u\renpy-6.99.13-sdk\renpy\audio\audio.py", line 960, in periodic_thread_main
    periodic_pass()
  File "E:\github_ics3u\renpy-6.99.13-sdk\renpy\audio\audio.py", line 917, in periodic_pass
    c.periodic()
  File "E:\github_ics3u\renpy-6.99.13-sdk\renpy\audio\audio.py", line 409, in periodic
    topf = load(self.file_prefix + filename + self.file_suffix)
  File "E:\github_ics3u\renpy-6.99.13-sdk\renpy\audio\audio.py", line 69, in load
    rv = renpy.loader.load(fn)
  File "E:\github_ics3u\renpy-6.99.13-sdk\renpy\loader.py", line 548, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'credits3.webm'.

Windows-7-6.1.7601-SP1
Ren'Py 6.99.13.2919
Fated To Bloom 1.0
